### ISSUE TITLE
Add chest removal from donkey and mule

### ISSUE THREAD

**Issue by Aeredren** [ReviversMC/unsaddle#4]
I didn't find any better place to post this so I thought: maybe opening an issue is fine.

Do you think it is do-able to also add the functionnality to "unchest" a donkey or mule ?

*very nice mod btw*

**Comment by NebelNidas** [comment]
Good suggestion, though I'm uncertain whether or not that's in scope of this mod. I'll try to see how difficult it is!

**Comment by venaminecraft** [comment]
Hello @NebelNidas, any update on this? 😊

**Comment by NebelNidas** [comment]
Sorry for the late response, I completely forgot about this feature request. 😅
Good news though, I've got the feature working locally and will publish the new version soon!

**Comment by venaminecraft** [comment]
Thank you so much - a great addition.
